name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Hoặc tên branch bạn đang dùng

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd DoAnWeb
            git pull
            sudo docker-compose down
            sudo docker-compose up --build -d
